# This file is machine-generated - editing it directly is not advised

[[FLOWMath]]
deps = ["OffsetArrays"]
git-tree-sha1 = "1f3d7db3d15a7f63a017cfbe3606cfdd3a3f1e42"
repo-rev = "master"
repo-url = "https://github.com/byuflowlab/FLOWMath.jl"
uuid = "6cb5d3fb-0fe8-4cc2-bd89-9fe0b19a99d3"
version = "0.1.0"

[[Libdl]]
uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[[LinearAlgebra]]
deps = ["Libdl"]
uuid = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[[OffsetArrays]]
git-tree-sha1 = "1ae707306f6e33dbb37d0742e08828562772b73f"
uuid = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
version = "0.11.2"
