name: Run tests

on:
  push:
    paths:
    - '**.jl'
    - '**.toml'
  pull_request:


jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['1.0', '1.3']
        julia-arch: [x64, x86]
        os: [ubuntu-latest, macOS-latest]
        exclude:
          - os: macOS-latest
            julia-arch: x86

    steps:
      - uses: actions/checkout@v1.0.0
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
      - run: julia -e 'using Pkg; Pkg.add(PackageSpec(url="https://github.com/byuflowlab/FLOWMath.jl"))'
      - uses: julia-actions/julia-runtest@master